#!/bin/bash

dir=`pwd`

if [ -e local/lib/libboost_unit_test_framework.so ] 
  then
    echo "boost.test already installed"
  else
    echo "Installing boost.test"
    curl -L -O http://sourceforge.net/projects/boost/files/boost/1.52.0/boost_1_52_0.tar.bz2
    rm -Rf boost_1_52_0
    tar --bzip2 -xf boost_1_52_0.tar.bz2
    cd boost_1_52_0
    ./bootstrap.sh --with-libraries=test --prefix=../local
    ./b2 install
    cd $dir
fi

setup=bin/setup.sh
echo 'export BOOST_INC_DIR='$dir'/local/include' >> $setup
echo 'export BOOST_LIB_DIR='$dir'/local/lib' >> $setup
echo 'export LD_LIBRARY_PATH='$dir'/local/lib:${LD_LIBRARY_PATH}' >> $setup

#
# csh version for make
#
setup=bin/setup
echo 'setenv BOOST_INC_DIR '$dir'/local/include' >> $setup
echo 'setenv BOOST_LIB_DIR '$dir'/local/lib' >> $setup
echo 'setenv LD_LIBRARY_PATH '$dir'/local/lib:${LD_LIBRARY_PATH}' >> $setup
