#!/bin/bash
#
# Need at least python 2.6 for the multiprocessing module,
# so use KIPAC installation at SLAC.
export PATH=/afs/slac/g/ki/software/python/2.6.6/bin:${PATH}

echo "running standard tests"
./phosim examples/star -c examples/nobackground
./validation/unittest

#echo "running boost.test unit tests"
#outdir=boosttests
#rm -Rf $outdir
#mkdir $outdir
#source bin/setup.sh
#cd source/ancillary
#./test_ancillary --output_format=xml --log_level=test_suite --report_level=no >& ../../$outdir/test_ancillary.xml

#./test_file_reader --output_format=xml --log_level=test_suite --report_level=no >& ../../$outdir/test_file_reader.xml
