#!/bin/csh -f
#
# ------------------------------------------------
#CLEAN UP SCRIPT
# ------------------------------------------------

set obshistid=$1

echo 'Cleaning up '$1

if ($obshistid != '') then 

rm -f *_${obshistid}*

rm -f output/*_${obshistid}*.fits*
rm -f work/*_${obshistid}*
rm -f work/logs/*_${obshistid}*
rm -f work/errors/*_${obshistid}*
rm -f work/output/*_${obshistid}*

endif

