#!/bin/csh -f
## @package phosim
## @file phosim
## @brief main script to run all validation tests
##
## @brief Created by:
## @author John R. Peterson (Purdue)
##
## @brief Modified by:
## @author En-Hsin Peng (Purdue)
##
## @warning This code is not fully validated
## and not ready for full release.  Please
## treat results with caution.
##

#validation/unittest >& validation/unittest_output
#cd source/ancillary/ ; test_phosim_parser < test.pars >> ../../validation/unittest_output ; cd ../../.
#cd source/ancillary/ ; test_readtext < test.txt >> ../../validation/unittest_output ; cd ../../.
#cd source/trim/ ; test_trim < test/test.pars >> ../../validation/unittest_output ; cd ../../.

test_unit >& validation/unittest_output
test_integration
