#############################################################################
# Generated by PAGE version 4.8.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {DejaVu Sans Mono} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {DejaVu Sans Mono} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr40
    set site_3_0 $base.scr37
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m37" -relief ridge -background {#d9d9d9} \
        -highlightbackground white -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 699x770+521+82
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "ClusterSubmit"
    vTcl:DefineAlias "$top" "ClusterSubmit" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {(-w) work directory(Required)} 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "ClusterSubmit" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify right \
        -text {(-o) output directory(Required)} 
    vTcl:DefineAlias "$top.lab45" "Label4" vTcl:WidgetProc "ClusterSubmit" 1
    checkbutton $top.che49 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Disable Running of Raytrace Tasks} -variable raytraceDisable 
    vTcl:DefineAlias "$top.che49" "DisableRaytraceButton" vTcl:WidgetProc "ClusterSubmit" 1
    checkbutton $top.che50 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Disable Running of E2ADC Tasks} -variable e2adcDisable \
        -width 279 
    vTcl:DefineAlias "$top.che50" "DisableE2ADCButton" vTcl:WidgetProc "ClusterSubmit" 1
    checkbutton $top.che51 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -overrelief flat -state active -text {Enable DMTCP checkpointing} \
        -variable dmtcpEnable 
    vTcl:DefineAlias "$top.che51" "DMTCPEnableButton" vTcl:WidgetProc "ClusterSubmit" 1
    checkbutton $top.che52 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -state active -text {Enable Internal phosim Checkpointing} \
        -variable intrnlChkptEnable 
    vTcl:DefineAlias "$top.che52" "Checkbutton5" vTcl:WidgetProc "ClusterSubmit" 1
    message $top.mes57 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -highlightthickness 2 \
        -justify center -relief raised \
        -text {This program generates and submits to a cluster the .slurm (or .pbs) jobs to generate the simulated LSST images for a visit using the phosim trim,raytrace and e2adc programs. It does this using the "dagman" and "*.submit" files that are generated by running phosim.py with the "-g condor" option.} \
        -width 599 
    vTcl:DefineAlias "$top.mes57" "Message1" vTcl:WidgetProc "ClusterSubmit" 1
    message $top.mes59 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify center \
        -relief raised \
        -text {The following options can be used to control in detail what is run on the cluster. If nothing is checked, a full set of phosim programs is submitted to process a complete visit.} \
        -width 479 
    vTcl:DefineAlias "$top.mes59" "Message2" vTcl:WidgetProc "ClusterSubmit" 1
    message $top.mes37 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify center \
        -relief groove \
        -text {Specifiy paths that were used with the phosim.py -w and -o options to generate the dagman and *.submit files for this visit.
} \
        -width 479 
    vTcl:DefineAlias "$top.mes37" "Message3" vTcl:WidgetProc "ClusterSubmit" 1
    button $top.but38 \
        -activebackground {#ff0003} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#00f300} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#ced9d4} -highlightcolor black \
        -text {Submit Command} -wraplength 100 
    vTcl:DefineAlias "$top.but38" "Submit" vTcl:WidgetProc "ClusterSubmit" 1
    bind $top.but38 <ButtonRelease-1> {
        lambda e: submitClusterSubmit(e)
    }
    entry $top.ent40 \
        -background white -font $::vTcl(fonts,vTcl:font14,object) \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable dagmanFilename 
    vTcl:DefineAlias "$top.ent40" "Entry3" vTcl:WidgetProc "ClusterSubmit" 1
    label $top.lab42 \
        -activebackground {#ffff00000000} -activeforeground {#ff0000} \
        -anchor w -background {#d9d9d9} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightcolor black -justify left \
        -text {dagman File Name(Required)} 
    vTcl:DefineAlias "$top.lab42" "Label1" vTcl:WidgetProc "ClusterSubmit" 1
    entry $top.ent37 \
        -background white -font $::vTcl(fonts,vTcl:font13,object) \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable workDirName 
    vTcl:DefineAlias "$top.ent37" "Entry1" vTcl:WidgetProc "ClusterSubmit" 1
    entry $top.ent38 \
        -background white -font $::vTcl(fonts,vTcl:font13,object) \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable outputDirName 
    vTcl:DefineAlias "$top.ent38" "Entry2" vTcl:WidgetProc "ClusterSubmit" 1
    checkbutton $top.che37 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -justify left \
        -text {Disable Running of Trim Tasks} -variable trimDisable \
        -width 262 
    vTcl:DefineAlias "$top.che37" "DisableTrimButton" vTcl:WidgetProc "ClusterSubmit" 1
    menu $top.m37 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font font9 -foreground {#000000} -tearoff 0 
    button $top.but39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Create cluster_submit Command} -wraplength 120 
    vTcl:DefineAlias "$top.but39" "createCmd" vTcl:WidgetProc "ClusterSubmit" 1
    bind $top.but39 <ButtonRelease-1> {
        lambda e: createCSCommand(e)
    }
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr40 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr40" "cmdText" vTcl:WidgetProc "ClusterSubmit" 1

    $top.scr40.01 configure -background white \
        -font font12 \
        -foreground black \
        -height 23 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -undo 1 \
        -width 10 \
        -wrap word
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but40" "Exit" vTcl:WidgetProc "ClusterSubmit" 1
    bind $top.but40 <ButtonRelease-1> {
        lambda e: quitExit(e)
    }
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr37 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr37" "statusText" vTcl:WidgetProc "ClusterSubmit" 1

    $top.scr37.01 configure -background white \
        -font font12 \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -undo 1 \
        -width 10 \
        -wrap word
    entry $top.ent39 \
        -background white -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#0031ff} -highlightcolor black -insertbackground black \
        -justify center -relief raised -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable CSTitle 
    vTcl:DefineAlias "$top.ent39" "TitleEntry" vTcl:WidgetProc "ClusterSubmit" 1
    radiobutton $top.rad37 \
        -activebackground {#d9d9d9} -anchor w -background {#d9d9d9} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightcolor black -justify left -text {Haswell Parition} \
        -value haswell -variable CoriPartition 
    vTcl:DefineAlias "$top.rad37" "Haswell" vTcl:WidgetProc "ClusterSubmit" 1
    radiobutton $top.rad38 \
        -activebackground {#d9d9d9} -anchor w -background {#d9d9d9} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightcolor black -justify left -text {KNL Partition} -value KNL \
        -variable CoriPartition 
    vTcl:DefineAlias "$top.rad38" "KNL" vTcl:WidgetProc "ClusterSubmit" 1
    label $top.lab39 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -text {For Cori as Host Only} 
    vTcl:DefineAlias "$top.lab39" "Label2" vTcl:WidgetProc "ClusterSubmit" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 50 -y 270 -width 235 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 50 -y 310 -width 242 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 60 -y 460 -width 284 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 60 -y 480 -width 279 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che51 \
        -in $top -x 360 -y 440 -anchor nw -bordermode ignore 
    place $top.che52 \
        -in $top -x 360 -y 460 -anchor nw -bordermode ignore 
    place $top.mes57 \
        -in $top -x 50 -y 50 -width 599 -relwidth 0 -height 83 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes59 \
        -in $top -x 80 -y 360 -width 479 -relwidth 0 -height 73 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes37 \
        -in $top -x 80 -y 220 -width 479 -relwidth 0 -height 53 -relheight 0 \
        -anchor w -bordermode ignore 
    place $top.but38 \
        -in $top -x 70 -y 660 -width 133 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent40 \
        -in $top -x 300 -y 140 -width 326 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 50 -y 150 -width 236 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent37 \
        -in $top -x 300 -y 260 -width 326 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent38 \
        -in $top -x 300 -y 300 -width 326 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che37 \
        -in $top -x 60 -y 440 -width 262 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 70 -y 580 -width 130 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr40 \
        -in $top -x 230 -y 590 -width 428 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 310 -y 730 -anchor nw -bordermode ignore 
    place $top.scr37 \
        -in $top -x 230 -y 660 -width 428 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent39 \
        -in $top -x 120 -y 10 -width 466 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.rad37 \
        -in $top -x 190 -y 530 -width 153 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.rad38 \
        -in $top -x 360 -y 530 -width 142 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 230 -y 510 -width 246 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

